# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           :year/:month/:day/:title.html

# Setup
title:               'Humane Being'
tagline:             ''
description:         'A blog about human factors in user experience engineering'
url:                 http://humanebeing.org
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Daniel Miller
  url:               http://danielsjourney.com
  email:             dealingwith@gmail.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]

plugins:
  - jekyll-remote-theme

remote_theme: benbalter/retlab
